# Bank 34, Vcco = Vadj
# Set the bank voltage for bank 34.


#set_property PACKAGE_PIN U20 [get_ports {JX1_LVDS_14_N}]
#set_property PACKAGE_PIN T20 [get_ports {JX1_LVDS_14_P}]
#set_property PACKAGE_PIN W20 [get_ports {JX1_LVDS_15_N}]
#set_property PACKAGE_PIN V20 [get_ports {JX1_LVDS_15_P}]
#set_property PACKAGE_PIN Y19 [get_ports {JX1_LVDS_16_N}]
#set_property PACKAGE_PIN Y18 [get_ports {JX1_LVDS_16_P}]
#set_property PACKAGE_PIN W16 [get_ports {JX1_LVDS_17_N}]
#set_property PACKAGE_PIN V16 [get_ports {JX1_LVDS_17_P}]
#set_property PACKAGE_PIN R17 [get_ports {JX1_LVDS_18_N}]
#set_property PACKAGE_PIN R16 [get_ports {JX1_LVDS_18_P}]
#set_property PACKAGE_PIN R18 [get_ports {JX1_LVDS_19_N}]
#set_property PACKAGE_PIN T17 [get_ports {JX1_LVDS_19_P}]
#set_property PACKAGE_PIN V13 [get_ports {JX1_LVDS_2_N}]
#set_property PACKAGE_PIN U13 [get_ports {JX1_LVDS_2_P}]
#set_property PACKAGE_PIN V18 [get_ports {JX1_LVDS_20_N}]
#set_property PACKAGE_PIN V17 [get_ports {JX1_LVDS_20_P}]
#set_property PACKAGE_PIN W19 [get_ports {JX1_LVDS_21_N}]
#set_property PACKAGE_PIN W18 [get_ports {JX1_LVDS_21_P}]
#set_property PACKAGE_PIN P18 [get_ports {JX1_LVDS_22_N}]
#set_property PACKAGE_PIN N17 [get_ports {JX1_LVDS_22_P}]
#set_property PACKAGE_PIN P16 [get_ports {JX1_LVDS_23_N}]
#set_property PACKAGE_PIN P15 [get_ports {JX1_LVDS_23_P}]
#set_property PACKAGE_PIN W13 [get_ports {JX1_LVDS_3_N}]
#set_property PACKAGE_PIN V12 [get_ports {JX1_LVDS_3_P}]
#set_property PACKAGE_PIN T15 [get_ports {JX1_LVDS_4_N}]
#set_property PACKAGE_PIN T14 [get_ports {JX1_LVDS_4_P}]
#set_property PACKAGE_PIN R14 [get_ports {JX1_LVDS_5_N}]
#set_property PACKAGE_PIN P14 [get_ports {JX1_LVDS_5_P}]
#set_property PACKAGE_PIN Y17 [get_ports {JX1_LVDS_6_N}]
#set_property PACKAGE_PIN Y16 [get_ports {JX1_LVDS_6_P}]
#set_property PACKAGE_PIN Y14 [get_ports {JX1_LVDS_7_N}]
#set_property PACKAGE_PIN W14 [get_ports {JX1_LVDS_7_P}]
#set_property PACKAGE_PIN U17 [get_ports {JX1_LVDS_8_N}]
#set_property PACKAGE_PIN T16 [get_ports {JX1_LVDS_8_P}]
#set_property PACKAGE_PIN W15 [get_ports {JX1_LVDS_9_N}]
#set_property PACKAGE_PIN V15 [get_ports {JX1_LVDS_9_P}]
#set_property PACKAGE_PIN R19 [get_ports {JX1_SE_0}]
#set_property PACKAGE_PIN T19 [get_ports {JX1_SE_1}]

# Bank 35, Vcco = Vadj
# Set the bank voltage for bank 35.

set_property PACKAGE_PIN B20 [get_ports SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SCLK]
set_property PACKAGE_PIN C20 [get_ports SS]
set_property IOSTANDARD LVCMOS33 [get_ports SS]
#set_property PACKAGE_PIN A20 [get_ports {JX2_LVDS_1_N}]
#set_property PACKAGE_PIN B19 [get_ports {JX2_LVDS_1_P}]
#set_property PACKAGE_PIN L17 [get_ports {JX2_LVDS_10_N}]
#set_property PACKAGE_PIN L16 [get_ports {JX2_LVDS_10_P}]
#set_property PACKAGE_PIN K18 [get_ports {JX2_LVDS_11_N}]
#set_property PACKAGE_PIN K17 [get_ports {JX2_LVDS_11_P}]
#set_property PACKAGE_PIN H17 [get_ports {JX2_LVDS_12_N}]
#set_property PACKAGE_PIN H16 [get_ports {JX2_LVDS_12_P}]
#set_property PACKAGE_PIN H18 [get_ports {JX2_LVDS_13_N}]
#set_property PACKAGE_PIN J18 [get_ports {JX2_LVDS_13_P}]
#set_property PACKAGE_PIN G18 [get_ports {JX2_LVDS_14_N}]
#set_property PACKAGE_PIN G17 [get_ports {JX2_LVDS_14_P}]
#set_property PACKAGE_PIN F20 [get_ports {JX2_LVDS_15_N}]
#set_property PACKAGE_PIN F19 [get_ports {JX2_LVDS_15_P}]
#set_property PACKAGE_PIN G20 [get_ports {JX2_LVDS_16_N}]
#set_property PACKAGE_PIN G19 [get_ports {JX2_LVDS_16_P}]
#set_property PACKAGE_PIN H20 [get_ports {JX2_LVDS_17_N}]
#set_property PACKAGE_PIN J20 [get_ports {JX2_LVDS_17_P}]
#set_property PACKAGE_PIN J14 [get_ports {JX2_LVDS_18_N}]
#set_property PACKAGE_PIN K14 [get_ports {JX2_LVDS_18_P}]
#set_property PACKAGE_PIN G15 [get_ports {JX2_LVDS_19_N}]
#set_property PACKAGE_PIN H15 [get_ports {JX2_LVDS_19_P}]
#set_property PACKAGE_PIN D18 [get_ports {JX2_LVDS_2_N}]
set_property PACKAGE_PIN E17 [get_ports MISO]
set_property IOSTANDARD LVCMOS33 [get_ports MISO]
#set_property PACKAGE_PIN N16 [get_ports {JX2_LVDS_20_N}]
#set_property PACKAGE_PIN N15 [get_ports {JX2_LVDS_20_P}]
#set_property PACKAGE_PIN L15 [get_ports {JX2_LVDS_21_N}]
#set_property PACKAGE_PIN L14 [get_ports {JX2_LVDS_21_P}]
#set_property PACKAGE_PIN M15 [get_ports {JX2_LVDS_22_N}]
#set_property PACKAGE_PIN M14 [get_ports {JX2_LVDS_22_P}]
#set_property PACKAGE_PIN J16 [get_ports {JX2_LVDS_23_N}]
#set_property PACKAGE_PIN K16 [get_ports {JX2_LVDS_23_P}]
#set_property PACKAGE_PIN D20 [get_ports {JX2_LVDS_3_N}]
#set_property PACKAGE_PIN D19 [get_ports {JX2_LVDS_3_P}]
#set_property PACKAGE_PIN E19 [get_ports {JX2_LVDS_4_N}]
#set_property PACKAGE_PIN E18 [get_ports {JX2_LVDS_4_P}]
#set_property PACKAGE_PIN F17 [get_ports {JX2_LVDS_5_N}]
#set_property PACKAGE_PIN F16 [get_ports {JX2_LVDS_5_P}]
#set_property PACKAGE_PIN L20 [get_ports {JX2_LVDS_6_N}]
#set_property PACKAGE_PIN L19 [get_ports {JX2_LVDS_6_P}]
#set_property PACKAGE_PIN M20 [get_ports {JX2_LVDS_7_N}]
#set_property PACKAGE_PIN M19 [get_ports {JX2_LVDS_7_P}]
#set_property PACKAGE_PIN M18 [get_ports {JX2_LVDS_8_N}]
#set_property PACKAGE_PIN M17 [get_ports {JX2_LVDS_8_P}]
#set_property PACKAGE_PIN J19 [get_ports {JX2_LVDS_9_N}]
#set_property PACKAGE_PIN K19 [get_ports {JX2_LVDS_9_P}]
#set_property PACKAGE_PIN G14 [get_ports {JX2_SE_0}]
#set_property PACKAGE_PIN J15 [get_ports {JX2_SE_1}]




set_property IOSTANDARD LVCMOS33 [get_ports MOSI]
set_property PACKAGE_PIN L19 [get_ports MOSI]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list TEST/design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {IFACE/STE/spi_transfer_length[0]} {IFACE/STE/spi_transfer_length[1]} {IFACE/STE/spi_transfer_length[2]} {IFACE/STE/spi_transfer_length[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {IFACE/STE/spi_delay[0]} {IFACE/STE/spi_delay[1]} {IFACE/STE/spi_delay[2]} {IFACE/STE/spi_delay[3]} {IFACE/STE/spi_delay[4]} {IFACE/STE/spi_delay[5]} {IFACE/STE/spi_delay[6]} {IFACE/STE/spi_delay[7]} {IFACE/STE/spi_delay[8]} {IFACE/STE/spi_delay[9]} {IFACE/STE/spi_delay[10]} {IFACE/STE/spi_delay[11]} {IFACE/STE/spi_delay[12]} {IFACE/STE/spi_delay[13]} {IFACE/STE/spi_delay[14]} {IFACE/STE/spi_delay[15]} {IFACE/STE/spi_delay[16]} {IFACE/STE/spi_delay[17]} {IFACE/STE/spi_delay[18]} {IFACE/STE/spi_delay[19]} {IFACE/STE/spi_delay[20]} {IFACE/STE/spi_delay[21]} {IFACE/STE/spi_delay[22]} {IFACE/STE/spi_delay[23]} {IFACE/STE/spi_delay[24]} {IFACE/STE/spi_delay[25]} {IFACE/STE/spi_delay[26]} {IFACE/STE/spi_delay[27]} {IFACE/STE/spi_delay[28]} {IFACE/STE/spi_delay[29]} {IFACE/STE/spi_delay[30]} {IFACE/STE/spi_delay[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {IFACE/STE/state[0]} {IFACE/STE/state[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {IFACE/STE/ss_delay_timer[0]} {IFACE/STE/ss_delay_timer[1]} {IFACE/STE/ss_delay_timer[2]} {IFACE/STE/ss_delay_timer[3]} {IFACE/STE/ss_delay_timer[4]} {IFACE/STE/ss_delay_timer[5]} {IFACE/STE/ss_delay_timer[6]} {IFACE/STE/ss_delay_timer[7]} {IFACE/STE/ss_delay_timer[8]} {IFACE/STE/ss_delay_timer[9]} {IFACE/STE/ss_delay_timer[10]} {IFACE/STE/ss_delay_timer[11]} {IFACE/STE/ss_delay_timer[12]} {IFACE/STE/ss_delay_timer[13]} {IFACE/STE/ss_delay_timer[14]} {IFACE/STE/ss_delay_timer[15]} {IFACE/STE/ss_delay_timer[16]} {IFACE/STE/ss_delay_timer[17]} {IFACE/STE/ss_delay_timer[18]} {IFACE/STE/ss_delay_timer[19]} {IFACE/STE/ss_delay_timer[20]} {IFACE/STE/ss_delay_timer[21]} {IFACE/STE/ss_delay_timer[22]} {IFACE/STE/ss_delay_timer[23]} {IFACE/STE/ss_delay_timer[24]} {IFACE/STE/ss_delay_timer[25]} {IFACE/STE/ss_delay_timer[26]} {IFACE/STE/ss_delay_timer[27]} {IFACE/STE/ss_delay_timer[28]} {IFACE/STE/ss_delay_timer[29]} {IFACE/STE/ss_delay_timer[30]} {IFACE/STE/ss_delay_timer[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list IFACE/STE/register_load]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list IFACE/STE/register_enable]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list IFACE/STE/spi_mode]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list IFACE/STE/spi_sclk]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list IFACE/STE/spi_start_transfer]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list IFACE/STE/transfer_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list IFACE/MOSI]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list IFACE/SCLK_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list IFACE/SS]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
