# Bank 34, Vcco = Vadj
# Set the bank voltage for bank 34.
set_property IOSTANDARD LVCMOS33 [get_ports -filter { IOBANK == 34 } ]


#set_property PACKAGE_PIN U20 [get_ports {JX1_LVDS_14_N}]
#set_property PACKAGE_PIN T20 [get_ports {JX1_LVDS_14_P}]
#set_property PACKAGE_PIN W20 [get_ports {JX1_LVDS_15_N}]
#set_property PACKAGE_PIN V20 [get_ports {JX1_LVDS_15_P}]
#set_property PACKAGE_PIN Y19 [get_ports {JX1_LVDS_16_N}]
#set_property PACKAGE_PIN Y18 [get_ports {JX1_LVDS_16_P}]
#set_property PACKAGE_PIN W16 [get_ports {JX1_LVDS_17_N}]
#set_property PACKAGE_PIN V16 [get_ports {JX1_LVDS_17_P}]
#set_property PACKAGE_PIN R17 [get_ports {JX1_LVDS_18_N}]
#set_property PACKAGE_PIN R16 [get_ports {JX1_LVDS_18_P}]
#set_property PACKAGE_PIN R18 [get_ports {JX1_LVDS_19_N}]
#set_property PACKAGE_PIN T17 [get_ports {JX1_LVDS_19_P}]
#set_property PACKAGE_PIN V13 [get_ports {JX1_LVDS_2_N}]
#set_property PACKAGE_PIN U13 [get_ports {JX1_LVDS_2_P}]
#set_property PACKAGE_PIN V18 [get_ports {JX1_LVDS_20_N}]
#set_property PACKAGE_PIN V17 [get_ports {JX1_LVDS_20_P}]
#set_property PACKAGE_PIN W19 [get_ports {JX1_LVDS_21_N}]
#set_property PACKAGE_PIN W18 [get_ports {JX1_LVDS_21_P}]
#set_property PACKAGE_PIN P18 [get_ports {JX1_LVDS_22_N}]
#set_property PACKAGE_PIN N17 [get_ports {JX1_LVDS_22_P}]
#set_property PACKAGE_PIN P16 [get_ports {JX1_LVDS_23_N}]
#set_property PACKAGE_PIN P15 [get_ports {JX1_LVDS_23_P}]
#set_property PACKAGE_PIN W13 [get_ports {JX1_LVDS_3_N}]
#set_property PACKAGE_PIN V12 [get_ports {JX1_LVDS_3_P}]
#set_property PACKAGE_PIN T15 [get_ports {JX1_LVDS_4_N}]
#set_property PACKAGE_PIN T14 [get_ports {JX1_LVDS_4_P}]
#set_property PACKAGE_PIN R14 [get_ports {JX1_LVDS_5_N}]
#set_property PACKAGE_PIN P14 [get_ports {JX1_LVDS_5_P}]
#set_property PACKAGE_PIN Y17 [get_ports {JX1_LVDS_6_N}]
#set_property PACKAGE_PIN Y16 [get_ports {JX1_LVDS_6_P}]
#set_property PACKAGE_PIN Y14 [get_ports {JX1_LVDS_7_N}]
#set_property PACKAGE_PIN W14 [get_ports {JX1_LVDS_7_P}]
#set_property PACKAGE_PIN U17 [get_ports {JX1_LVDS_8_N}]
#set_property PACKAGE_PIN T16 [get_ports {JX1_LVDS_8_P}]
#set_property PACKAGE_PIN W15 [get_ports {JX1_LVDS_9_N}]
#set_property PACKAGE_PIN V15 [get_ports {JX1_LVDS_9_P}]
#set_property PACKAGE_PIN R19 [get_ports {JX1_SE_0}]
#set_property PACKAGE_PIN T19 [get_ports {JX1_SE_1}]

# Bank 35, Vcco = Vadj
# Set the bank voltage for bank 35.
set_property IOSTANDARD LVCMOS33 [get_ports -filter { IOBANK == 35 } ]

set_property PACKAGE_PIN B20 [get_ports SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SCLK]
set_property PACKAGE_PIN C20 [get_ports SS]
set_property IOSTANDARD LVCMOS33 [get_ports SS]
#set_property PACKAGE_PIN A20 [get_ports {JX2_LVDS_1_N}]
#set_property PACKAGE_PIN B19 [get_ports {JX2_LVDS_1_P}]
#set_property PACKAGE_PIN L17 [get_ports {JX2_LVDS_10_N}]
#set_property PACKAGE_PIN L16 [get_ports {JX2_LVDS_10_P}]
#set_property PACKAGE_PIN K18 [get_ports {JX2_LVDS_11_N}]
#set_property PACKAGE_PIN K17 [get_ports {JX2_LVDS_11_P}]
#set_property PACKAGE_PIN H17 [get_ports {JX2_LVDS_12_N}]
#set_property PACKAGE_PIN H16 [get_ports {JX2_LVDS_12_P}]
#set_property PACKAGE_PIN H18 [get_ports {JX2_LVDS_13_N}]
#set_property PACKAGE_PIN J18 [get_ports {JX2_LVDS_13_P}]
#set_property PACKAGE_PIN G18 [get_ports {JX2_LVDS_14_N}]
#set_property PACKAGE_PIN G17 [get_ports {JX2_LVDS_14_P}]
#set_property PACKAGE_PIN F20 [get_ports {JX2_LVDS_15_N}]
#set_property PACKAGE_PIN F19 [get_ports {JX2_LVDS_15_P}]
#set_property PACKAGE_PIN G20 [get_ports {JX2_LVDS_16_N}]
#set_property PACKAGE_PIN G19 [get_ports {JX2_LVDS_16_P}]
#set_property PACKAGE_PIN H20 [get_ports {JX2_LVDS_17_N}]
#set_property PACKAGE_PIN J20 [get_ports {JX2_LVDS_17_P}]
#set_property PACKAGE_PIN J14 [get_ports {JX2_LVDS_18_N}]
#set_property PACKAGE_PIN K14 [get_ports {JX2_LVDS_18_P}]
#set_property PACKAGE_PIN G15 [get_ports {JX2_LVDS_19_N}]
#set_property PACKAGE_PIN H15 [get_ports {JX2_LVDS_19_P}]
#set_property PACKAGE_PIN D18 [get_ports {JX2_LVDS_2_N}]
set_property PACKAGE_PIN E17 [get_ports MISO]
set_property IOSTANDARD LVCMOS33 [get_ports MISO]
#set_property PACKAGE_PIN N16 [get_ports {JX2_LVDS_20_N}]
#set_property PACKAGE_PIN N15 [get_ports {JX2_LVDS_20_P}]
#set_property PACKAGE_PIN L15 [get_ports {JX2_LVDS_21_N}]
#set_property PACKAGE_PIN L14 [get_ports {JX2_LVDS_21_P}]
#set_property PACKAGE_PIN M15 [get_ports {JX2_LVDS_22_N}]
#set_property PACKAGE_PIN M14 [get_ports {JX2_LVDS_22_P}]
#set_property PACKAGE_PIN J16 [get_ports {JX2_LVDS_23_N}]
#set_property PACKAGE_PIN K16 [get_ports {JX2_LVDS_23_P}]
#set_property PACKAGE_PIN D20 [get_ports {JX2_LVDS_3_N}]
#set_property PACKAGE_PIN D19 [get_ports {JX2_LVDS_3_P}]
#set_property PACKAGE_PIN E19 [get_ports {JX2_LVDS_4_N}]
#set_property PACKAGE_PIN E18 [get_ports {JX2_LVDS_4_P}]
#set_property PACKAGE_PIN F17 [get_ports {JX2_LVDS_5_N}]
#set_property PACKAGE_PIN F16 [get_ports {JX2_LVDS_5_P}]
#set_property PACKAGE_PIN L20 [get_ports {JX2_LVDS_6_N}]
#set_property PACKAGE_PIN L19 [get_ports {JX2_LVDS_6_P}]
#set_property PACKAGE_PIN M20 [get_ports {JX2_LVDS_7_N}]
#set_property PACKAGE_PIN M19 [get_ports {JX2_LVDS_7_P}]
#set_property PACKAGE_PIN M18 [get_ports {JX2_LVDS_8_N}]
#set_property PACKAGE_PIN M17 [get_ports {JX2_LVDS_8_P}]
#set_property PACKAGE_PIN J19 [get_ports {JX2_LVDS_9_N}]
#set_property PACKAGE_PIN K19 [get_ports {JX2_LVDS_9_P}]
#set_property PACKAGE_PIN G14 [get_ports {JX2_SE_0}]
#set_property PACKAGE_PIN J15 [get_ports {JX2_SE_1}]

set_property MARK_DEBUG false [get_nets UUT/int_start_conversion]
set_property MARK_DEBUG false [get_nets {UUT/raw_spi_data[0][0]}]
set_property MARK_DEBUG false [get_nets {UUT/raw_spi_data[0][2]}]
set_property MARK_DEBUG false [get_nets {UUT/raw_spi_data[0][3]}]
set_property MARK_DEBUG false [get_nets {UUT/raw_spi_data[0][6]}]
set_property MARK_DEBUG false [get_nets {UUT/raw_spi_data[0][8]}]
set_property MARK_DEBUG false [get_nets {UUT/raw_spi_data[0][11]}]
set_property MARK_DEBUG false [get_nets {UUT/raw_spi_data[0][12]}]
set_property MARK_DEBUG false [get_nets {UUT/raw_spi_data[0][15]}]
set_property MARK_DEBUG false [get_nets {UUT/raw_spi_data[0][1]}]
set_property MARK_DEBUG false [get_nets {UUT/raw_spi_data[0][4]}]
set_property MARK_DEBUG false [get_nets {UUT/raw_spi_data[0][5]}]
set_property MARK_DEBUG false [get_nets {UUT/raw_spi_data[0][7]}]
set_property MARK_DEBUG false [get_nets {UUT/raw_spi_data[0][9]}]
set_property MARK_DEBUG false [get_nets {UUT/raw_spi_data[0][10]}]
set_property MARK_DEBUG false [get_nets {UUT/raw_spi_data[0][13]}]
set_property MARK_DEBUG false [get_nets {UUT/raw_spi_data[0][14]}]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list TEST/design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {UUT/simple_bus\\.sb_address[0]} {UUT/simple_bus\\.sb_address[1]} {UUT/simple_bus\\.sb_address[2]} {UUT/simple_bus\\.sb_address[3]} {UUT/simple_bus\\.sb_address[4]} {UUT/simple_bus\\.sb_address[5]} {UUT/simple_bus\\.sb_address[6]} {UUT/simple_bus\\.sb_address[7]} {UUT/simple_bus\\.sb_address[8]} {UUT/simple_bus\\.sb_address[9]} {UUT/simple_bus\\.sb_address[10]} {UUT/simple_bus\\.sb_address[11]} {UUT/simple_bus\\.sb_address[12]} {UUT/simple_bus\\.sb_address[13]} {UUT/simple_bus\\.sb_address[14]} {UUT/simple_bus\\.sb_address[15]} {UUT/simple_bus\\.sb_address[16]} {UUT/simple_bus\\.sb_address[17]} {UUT/simple_bus\\.sb_address[18]} {UUT/simple_bus\\.sb_address[19]} {UUT/simple_bus\\.sb_address[20]} {UUT/simple_bus\\.sb_address[21]} {UUT/simple_bus\\.sb_address[22]} {UUT/simple_bus\\.sb_address[23]} {UUT/simple_bus\\.sb_address[24]} {UUT/simple_bus\\.sb_address[25]} {UUT/simple_bus\\.sb_address[26]} {UUT/simple_bus\\.sb_address[27]} {UUT/simple_bus\\.sb_address[28]} {UUT/simple_bus\\.sb_address[29]} {UUT/simple_bus\\.sb_address[30]} {UUT/simple_bus\\.sb_address[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 15 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {UUT/raw_spi_data[0][0]} {UUT/raw_spi_data[0][1]} {UUT/raw_spi_data[0][2]} {UUT/raw_spi_data[0][3]} {UUT/raw_spi_data[0][4]} {UUT/raw_spi_data[0][5]} {UUT/raw_spi_data[0][6]} {UUT/raw_spi_data[0][7]} {UUT/raw_spi_data[0][8]} {UUT/raw_spi_data[0][9]} {UUT/raw_spi_data[0][10]} {UUT/raw_spi_data[0][11]} {UUT/raw_spi_data[0][12]} {UUT/raw_spi_data[0][13]} {UUT/raw_spi_data[0][14]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {UUT/simple_bus\\.sb_write_data[0]} {UUT/simple_bus\\.sb_write_data[1]} {UUT/simple_bus\\.sb_write_data[2]} {UUT/simple_bus\\.sb_write_data[3]} {UUT/simple_bus\\.sb_write_data[4]} {UUT/simple_bus\\.sb_write_data[5]} {UUT/simple_bus\\.sb_write_data[6]} {UUT/simple_bus\\.sb_write_data[7]} {UUT/simple_bus\\.sb_write_data[8]} {UUT/simple_bus\\.sb_write_data[9]} {UUT/simple_bus\\.sb_write_data[10]} {UUT/simple_bus\\.sb_write_data[11]} {UUT/simple_bus\\.sb_write_data[12]} {UUT/simple_bus\\.sb_write_data[13]} {UUT/simple_bus\\.sb_write_data[14]} {UUT/simple_bus\\.sb_write_data[15]} {UUT/simple_bus\\.sb_write_data[16]} {UUT/simple_bus\\.sb_write_data[17]} {UUT/simple_bus\\.sb_write_data[18]} {UUT/simple_bus\\.sb_write_data[19]} {UUT/simple_bus\\.sb_write_data[20]} {UUT/simple_bus\\.sb_write_data[21]} {UUT/simple_bus\\.sb_write_data[22]} {UUT/simple_bus\\.sb_write_data[23]} {UUT/simple_bus\\.sb_write_data[24]} {UUT/simple_bus\\.sb_write_data[25]} {UUT/simple_bus\\.sb_write_data[26]} {UUT/simple_bus\\.sb_write_data[27]} {UUT/simple_bus\\.sb_write_data[28]} {UUT/simple_bus\\.sb_write_data[29]} {UUT/simple_bus\\.sb_write_data[30]} {UUT/simple_bus\\.sb_write_data[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list UUT/int_start_conversion]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
