#!/usr/bin/python
import jinja2
from sys import argv
from os import path


if len(argv)<2:
    print(f'USAGE: {__file__} [sim duration]')
    exit()


base_path = path.dirname(path.realpath(__file__))
templateLoader = jinja2.FileSystemLoader(searchpath=base_path)
templateEnv = jinja2.Environment(loader=templateLoader)
TEMPLATE_FILE = "sim_tcl.template"
template = templateEnv.get_template(TEMPLATE_FILE)

fields = {
    "result_filename":"results.vcd",
    "sim_duration":argv[1]
}

outputText = template.render(fields)  # this is where to put args to the template renderer
outputText = "### THIS FILE IS AUTOGENERATED, DO NOT MODIFY, AS IT WILL BE REWRITTEN NEXT TIME, MODIFY TEMPLATE####\n"+outputText

with open("run_sim.tcl", "w") as fh:
    fh.write(outputText)